# Site settings
title: Matt Dennett
email: dennett.matthew+gh@gmail.com
description:
  Matt's Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# About/contact
twitter:            'https://twitter.com'
linkedin:           'https://www.linkedin.com/in/matthew-dennett'
github:             'https://github.com/matthewdennett'

show_excerpts: true
excerpt_separator: <!--more-->
show_related_tags: true


collections:
  tagged:
    output: true
    permalink: /tagged/:path/
  education:
    output: true
    permalink: /education/:path/
  projects:
    output: true
    permalink: /projects/:path/
  work_experience:
    output: true
    permalink: /work_experience/:path/
  certifications:
    output: true
    permalink: /certifications/:path/

# Build settings
markdown: kramdown
permalink: /entries/:year/:month/:day/:title
highlighter: rouge
plugins: ["jemoji"]

# Custom vars
version:             1.1.0
google_analytics_id: G-EVB4GQGVC9